services:
  ui:
    image: couryrr/docker-volume-ui:latest
    ports: 
      - "80:3000"
    depends_on:
      - backend
  backend:
    image: couryrr/docker-volume-backend:latest
    ports: 
      - "8080:8080"
  
