services:
  ui:
    image: couryrr/docker-volume-ui:local
    build: 
      context: ./ui
      dockerfile: Dockerfile
      target: nonprod
    volumes:
      - ./ui/public:/app/public
    ports: 
      - "80:3000"
    depends_on:
      - backend
  backend:
    image: couryrr/docker-volume-backend:local
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend/bin:/app/bin
    ports: 
      - "8080:8080"
  
