FROM golang:1.23-bookworm

RUN apt-get update && \
    apt-get upgrade -y && \ 
    apt-get install inotify-tools -y

WORKDIR /app

COPY ./scripts /app/scripts

ENTRYPOINT ["bash","/app/scripts/watch_and_reload.sh"]

