FROM node:22-slim

RUN apt-get update && apt-get upgrade -y --force-yes && mkdir -p ./app/public

WORKDIR /app

COPY package.json package.json

RUN npm i

VOLUME ./app/public

EXPOSE 3000

ENTRYPOINT ["npx", "http-server", "-p", "3000"]
